dat<-read.csv("./brown.tfa",sep=" ",header=FALSE)
plot(dat$V1, dat$V4)
dat1<-read.csv("./eeg.tfa",sep=" ",header=FALSE)
plot(dat1$V1, dat1$V4, col= "black", ylab="Fourth column", xlab="First column")
points(dat$V1, dat$V4, col= "red")
plot(dat1$V1, dat1$V4, col= "black", ylab="Fourth column", xlab="First column")
points(dat$V1, dat$V4, col= "red")
plot(dat1$V1, dat1$V4, col= "black", ylab="Fourth column", xlab="First column", ylim=c(0.8,1.2))
points(dat$V1, dat$V4, col= "red")
plot(dat1$V1, dat1$V4, col= "black", ylab="Fourth column", xlab="First column", ylim=c(0.95,1.2))
points(dat$V1, dat$V4, col= "red")
plot(dat1$V1, dat1$V4, col= "black", ylab="Fourth column", xlab="First column", ylim=c(0.95,1.05))
points(dat$V1, dat$V4, col= "red")
plot(dat1$V1, dat1$V4, col= "black", ylab="Fourth column", xlab="First column", ylim=c(0.97,1.02))
points(dat$V1, dat$V4, col= "red")
leg
legend("bottomright",legend=c("EEG","Brownian"),col=c("black","red"))
legend("bottomright",legend=c("EEG","Brownian"),col=c("black","red"),pch=1)
png("./figure.png",width=1980,height=1280,res=300)
plot(dat1$V1, dat1$V4, col= "black", ylab="Fourth column", xlab="First column", ylim=c(0.97,1.02))
points(dat$V1, dat$V4, col= "red")
legend("bottomright",legend=c("EEG","Brownian"),col=c("black","red"),pch=1)
dev.off()
savehistory("./log.R")
